In [15]:
import numpy as np
import pandas as pd

np.random.seed(123)

n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [16]:
n_class_0, n_class_1

(900, 100)

In [17]:
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [18]:
df=pd.concat([class_0, class_1]).reset_index(drop=True)

In [19]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [20]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [21]:
## Up-Sampling: increase the number of minority

df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [25]:
from sklearn.utils import resample
df_minority_upsampled=resample(df_minority, replace=True, n_samples=len(df_majority), random_state=42)

In [27]:
df_minority_upsampled.shape

(900, 3)

In [28]:
df_unsampled=pd.concat([df_majority, df_minority_upsampled])

In [29]:
df_unsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [30]:
## Down-Sampling: we reduce the number of majority datapoints

import numpy as np
import pandas as pd

np.random.seed(123)

n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

df=pd.concat([class_0, class_1]).reset_index(drop=True)

df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [31]:
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [32]:
from sklearn.utils import resample
df_majority_downsampled=resample(df_majority, replace=False, n_samples=len(df_minority), random_state=42)

In [33]:
df_majority_downsampled.shape

(100, 3)

In [34]:
df_downsampled=pd.concat([df_minority, df_majority_downsampled])

In [35]:
df_downsampled['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64